### PR TITLE
Fix seanhenry/MockGenerator#2 by adding documentation in the 'Swift' intention category

### PR DESCRIPTION
**Pull request by codebrewer**
The intention description and example usage are taken from the project readme.

### CODE REVIEW

**Comment by codebrewer** [comment]
Useful looking plugin, thanks!

Here's how the doc looks:

screenshot 2017-06-27 08 12 02

Swift syntax highlighting appears not to be supported yet (it's not for the other, JetBrains, intention either) but maybe that'll come in time.

**Comment by seanhenry** [comment]
This looks great. Thanks for contributing! 

I had seen this error but wasn't sure how to go about fixing it. I will rebuild the plugin and send it to JetBrains today.

**Comment by seanhenry** [comment]
@codebrewer This update has been accepted by JetBrains and should appear in AppCode now 🎉

**Comment by codebrewer** [comment]
:thumbsup:

It's been a while since I updated a plugin but I don't recall it ever taking very long to become available. Maybe the review process is more thorough these days...

**Pull request merged**
